[server.pv.error]
no_permissions = "%cDésolé, mais vous n'êtes pas autorisé à exécuter cette commande. Veuillez contacter les administrateurs du serveur si vous pensez que c'est une erreur."
player_only_command = "Seuls les joueurs peuvent exécuter cette commande"
player_not_found = "Joueur introuvable"
mod_missing_kick_message = """
Désolé, vous devez installer le mod Plasmo Voice pour jouer sur ce serveur.
Télécharger ici : https://modrinth.com/plugin/plasmo-voice"""
version_not_supported = "Désolé, votre version Plasmo Voice n'est pas prise en charge sur ce serveur. %s"
version_not_supported_click = "Téléchargez la version supportée"
version_not_supported_hover = "%s"

[server.pv.mutes]
empty_reason = "non spécifié"
temporarily_muted = "Vous avez été rendu muet %1$s. Raison : %2$s"
permanently_muted = "Vous avez été rendu muet de façon permanente. Raison : %s"
unmuted = "Vous n'êtes plus muet"

  [server.pv.mutes.durations]
  seconds = "pour %s secondes"
  minutes = "pour %s minutes"
  hours = "pour %s heures"
  days = "pour %s jours"
  weeks = "pour %s semaines"

[server.pv.command.mute]
usage = "Utilisation: /vmute <joueur> [durée] [raison]"
already_muted = "%s est déjà muet"
temporarily_muted = "%1$s rendu muet. Raison : %3$s"
permanently_muted = "%1$s est rendu muet en permanence. Raison : %2$s"

[server.pv.command.unmute]
usage = "Utilisation : /vunmute <joueur>"
not_muted = "%s n'est pas muet"
unmuted = "%s n'est plus muet."

[server.pv.command.mute_list]
header = "Joueurs muets :"
entry = "%1$s, expire : %2$s. Raison : %3$s"
entry_muted_by = "%1$s rendu muet par %2$s, expire : %3$s. Raison : %4$s"
empty = "Aucun joueur n'est muet"
expire_at = "%1$s à %2$s"
never_expires = "jamais"
expiration_date = "dd.MM.yyyy"
expiration_time = "HH:mm:ss"

[server.pv.command.list]
message = "Clients (%1$s/%2$s) : %3$s"
empty = "aucun joueur avec Plasmo Voice installé"

[server.pv.command.reconnect]
message = "Paquet de reconnexion envoyé"

[server.pv.command.reload]
message = "Configuration rechargée"

[client.pv.activation]
proximity = "Proximité"
