debug = false
disable_crowdin = false
check_for_updates = true

[activations.4aec07ba-d109-3345-9a0a-92022a116cd0]
toggle = false
type = "VOICE"
[[key_bindings]]
name = "key.plasmovoice.general.mute_microphone"
any_context = false
category = "key.plasmovoice.general"

[[key_bindings.keys]]
code = 342
type = "KEYSYM"

[[key_bindings]]
name = "key.plasmovoice.general.disable_voice"
any_context = false
category = "key.plasmovoice.general"

[[key_bindings.keys]]
code = 77
type = "KEYSYM"

[[key_bindings]]
keys = []
name = "key.plasmovoice.proximity.ptt"
any_context = true
category = "hidden"

[servers.8d623f3d-867d-4552-9687-1909bfbc482a.distances]
4aec07ba-d109-3345-9a0a-92022a116cd0 = 32
[servers.9d7641da-8c3a-4363-b50f-7e98558e48fe.distances]
4aec07ba-d109-3345-9a0a-92022a116cd0 = 32

[addons.pv-addon-soundphysics]
"gui.plasmovoice.soundphysics.mic_reverb_volume" = 1.0
"gui.plasmovoice.soundphysics.enabled" = true
"gui.plasmovoice.soundphysics.mic_reverb" = true

[voice]
disabled = false
microphone_disabled = true
activation_threshold = -30.0
input_device = ""
output_device = ""
disable_input_device = false
use_javax_input = false
microphone_volume = 1.0
noise_suppression = true
volume = 1.0
compressor_limiter = true
sound_occlusion = false
directional_sources = false
hrtf = false
stereo_capture = false

[voice.volumes.source_df919179-a842-4797-b3cf-3391723944ec]
volume = 1.0
[voice.volumes.source_e8bc68e4-8be3-337a-87b2-dfb96c80e9f2]
volume = 1.0
[voice.volumes.source_a8611a9d-502f-35cb-a33c-dfff32a10d0e]
volume = 1.0
[voice.volumes.source_b8ef07fc-caa3-42dc-a823-6e1dfc1f0dd7]
volume = 1.0
[voice.volumes.source_605ed738-0258-310c-8d90-71663597c5ef]
volume = 1.0
[voice.volumes.source_aa5c85d9-b786-38b5-a504-a476cf974e46]
volume = 1.0
[voice.volumes.source_f13a351e-729e-4eab-bb70-6eac887d777d]
volume = 1.0
[voice.volumes.source_c315750c-6718-3c1b-b9dc-82a6a2eb0569]
volume = 1.0
[voice.volumes.source_00b63a90-f32c-4c81-9b9a-67e816b8af31]
volume = 1.0
[voice.volumes.source_3b8bddb4-c9ce-358a-85ab-3c728022756e]
volume = 1.0
[voice.volumes.source_ecf926eb-022d-3605-8668-c162c767eb2a]
volume = 1.0
[voice.volumes.source_37ec4142-ee68-32cc-931c-d30ef52893e8]
volume = 1.0
[voice.volumes.source_8621b20e-a1f5-433e-843b-adbf15a67b28]
volume = 1.0
[voice.volumes.source_3e91b26b-d71a-32ce-92d4-546f6833466a]
volume = 1.0
[voice.volumes.source_ade06771-3dc4-3cf1-9203-27e22dace9fd]
volume = 1.0
[voice.volumes.source_1263e1b7-b6c1-4ea3-b1ce-f984cbdde5e7]
volume = 1.0
[voice.volumes.source_3dddfbc1-dc32-3f9c-837a-23c49dfc6c32]
volume = 1.0
[voice.volumes.source_cec75746-dcb1-4c29-95dd-757d6b10d50f]
volume = 1.0
[voice.volumes.source_e1a5a1f2-e680-45b9-91e1-f0d7778e367d]
volume = 1.0
[voice.volumes.proximity]
volume = 1.0
[voice.volumes.source_fde765aa-5efc-4324-acc5-235f7016cb26]
volume = 1.0
[voice.volumes.source_ee52f7d1-d0f5-4395-8114-13aece66c88a]
volume = 1.0
[voice.volumes.source_20ba824e-b81b-42f2-853b-5b7ed81fa7d6]
volume = 1.0
[voice.volumes.source_da919b2f-cf24-313b-98cf-9077b0449580]
volume = 1.0
[voice.volumes.source_61d0b204-04a6-3ad9-9b70-f8c0555fa038]
volume = 1.0

[advanced]
visualize_voice_distance = true
visualize_voice_distance_on_join = false
compressor_threshold = -10
limiter_threshold = -6
directional_sources_angle = 145
stereo_sources_to_mono = false
panning = true
camera_sound_listener = true
exponential_volume_slider = true
exponential_distance_gain = true

[overlay]
show_activation_icon = true
activation_icon_position = "BOTTOM_CENTER"
show_source_icons = 0
show_static_source_icons = true
overlay_enabled = true
overlay_position = "TOP_LEFT"
overlay_style = "NAME_SKIN"

[overlay.source_states]
proximity = "OFF"
